### ISSUE TITLE
Availability & format of data file

### ISSUE THREAD

**Issue by TroyChicago** [OmriTreidel/cmprsk#5]
I am wondering what your data file looks like, and would you be able to share the 'test_set.csv' file that you used to test the code?
I am trying to figure out how to arrange my data file that contains -- time to events, events, and ~ 10 other predictors/features.
Cheers.

**Comment by OmriTreidel** [comment]
I think it will be helpful to look at the tests https://github.com/OmriTreidel/cmprsk/blob/master/cmprsk/tests/test_cmprsk.py#L13 where a test dataframe is constructed. 

The csv file would have predictor columns x1, x2 ... xN, ftime (failure time) and fstatus (failure status)

**Comment by TroyChicago** [comment]
Great. Thanks for the headsup!
